### ISSUE TITLE
Freeze+Crash on some android devices with version 8.0.0+

### ISSUE THREAD

**Issue by dustinaux** [openfl/openfl#1900] opened 2018-05-25 00:36 UTC
I've had reports of my game freezing and crashing on some android devices, and after a lot of back and forth between customers I've found the issue lies with the upgrade from openfl 7.1.2 to 8.0.0. Even the latest openfl 8.1.1/lime 6.3.1 was tested as well and crashes. Given that openfl 7.1.2 -> 8.0.0 also requires a lime upgrade from 6.2.0 to 6.3.0 it is unclear if the issue lies with openfl or lime.

Unfortunately I was never able to reproduce the issue myself on any of the 4 android devices that I own, and many other users experienced no problems with openfl 8.0.0+. From google play statistics of my game's installs and updates from users, it's probably a safe assumption to say a few hundred+ other devices are unaffected, given those users have little reason to contact me if everything is fine. So from that I'd estimate affected devices in use are probably <5% so it seems to be a fairly uncommon bug.

Here are the affected devices' model id and name:

1. camellia		ZTE Z833
2. s3_h60			-
3. ASUS_Z00L_93	Asus ZenFone 2 Laser (ZE550KL)
4. *HWH1611-Q	Huawei Copper Plus
5. *1606			Vivo Y53
6. *TB-7703X		Lenovo TAB3 7 Plus

The latest update I've just published rolls back to lime 6.2.0/openfl 7.1.2 and things seem to be running smoothly for all users now. The last three with * are still unconfirmed whether or not the rollback fixed the issue but the top three have all confirmed the game runs fine with 7.1.2.

At first I though the common link between devices may be OpenGL 3.0 but one of my old devices has that and has no problem. Android OS versions are varied on the affected devices and the same OS versions work on other devices so that doesn't seem to be a factor either.

Personally I've rolled back to 7.1.2 and things seem to be working but I wanted to post the issue here.

**Comment by dustinaux** [comment] 2018-05-25 00:56
A very helpful user (with the s3_h60 device) who happened to be a professional QA tester supplied logcat logs and a screen recording for each of lime 6.2.0/openfl 7.1.2, 6.3.0/8.0.0, and 6.3.1/8.1.1 builds which I am attaching here. In each build the only change is the version of lime and openfl.

[openfl_8.0.0_crash reports.zip](https://github.com/openfl/openfl/files/2037558/openfl_8.0.0_crash.reports.zip)

In the videos you'll notice that 7.1.2 is the only one that works, with the game's text not displaying being an unrelated side-effect in my own code from the rollback. 8.0.0 and 8.1.1 both freeze during my logo splash screen or as it is fading out.

I know very little on most of the logcat info but you can ctrl+f "trace" to find my trace statements from the game to find exactly when it launches in case those logs are helpful. I was not able to pinpoint an exact function but given the videos and description of the freeze it seems more like a massive memory leak resulting in an unresponsive phone. In the initial report the user said the phone became so unresponsive that he had to physically remove the battery.

**Comment by jgranick** [comment] 2018-05-25 02:34
We updated SDL to the latest version, actually this commit in the dev version: https://hg.libsdl.org/SDL/rev/b0ed2c515be0

SDL on Android updated to a newer minimum API level, so I also updated our target native NDK API level. This means that all native extensions and applications for Android may require a clean build (and a newish NDK, like r13b) in order to target current devices.

I also added a workaround for a bad standard library implementation of wide character to multi-byte string conversion: https://github.com/openfl/lime/commit/51ed111bef6f8a6fb54326583353ebabd244f1da

It's unfortunate we cannot reproduce personally

**Comment by dustinaux** [comment] 2018-05-25 16:49
To add some more info I was actually using Android NDK r13b, and the crashes were happening with clean builds too.

**Comment by jgranick** [comment] 2018-10-15 19:07
Although its super important if there are reasons why older devices are crashing, I'm closing this issue for now, as I can't think of anything actionable. If you have heard any more details, or anything more we could use to try and resolve any issues, please let me know! Otherwise, it's possible that we've increased our minimum required OS version, and users with older devices got upgraded when their devices were not compatible

**Closed by jgranick** 2018-10-15 19:07 UTC
