### ISSUE TITLE
Sound cutting out after 256 plays on windows cpp target

### ISSUE THREAD

**Issue by pizzamakesgames** [openfl/openfl#962] opened 2015-12-12 12:08 UTC
Using HaxeFlixel, typing out text letter by letter with FlxTypeText, playing a sound for each character, the typing sound effect cuts out exactly after the 255th character, with the music and any other sound effect cutting out as well shortly after.

Debugging through cmd, it throws these two errors:

<img src="http://i.imgur.com/VZRKCnQ.png" width="672" height="334">

The sound comes back on various actions like un/refocusing the game window or randomly on it's own.

Weirdly,this error won't happen when setting Windows 7's color scheme to basic, disabling aero.

My best guess is the sound using a new channel each time it's played, where it should just be re-using a single channel, as it's only a single sound effect restarting over and over without ever overlapping itself. I don't understand enough about the magic behind HaxeFlixel and it's components to validate that assumption, though.

If you want to try it for yourself, you can do so using the FlxTypeText demo from the flixel-demos repository, or really just playing any sound for more than 255 times in any project.

Here is the [haxeflixel forums thread](http://haxeflixel.com/forum/?place=msg%2Fhaxeflixel%2F-IThDPZvhqc%2FKAO2mc_GCQAJ) and [haxeflixel github issue](https://github.com/HaxeFlixel/flixel/issues/1645) on the problem.

**Comment by Gama11** [comment] 2015-12-20 22:42
[This](https://github.com/HaxeFlixel/flixel/issues/1645#issuecomment-164076734) is the relevant comment from HaxeFlixel/flixel#1645 reproducing this in pure OpenFL.

**Comment by azrafe7** [comment] 2015-12-22 11:31
Maybe I've found a way to solve this (at least it seems to work for me).

Change [`bool OpenALChannel::isComplete()`](https://github.com/openfl/lime/blob/bc30dc76451ca8355f34751380ef449414b304ec/legacy/project/src/openal/OpenALSound.cpp#L265) to:
```haxe
   bool OpenALChannel::isComplete()
   {
      bool complete = false;
	  
	  if (mUseStream)
      {
         if -(mStream)
         {
            mStream->update();
            complete = !(mStream->isActive());
         }
         else
         {
            complete = true;
         }
      }
      else if (!mSourceID)
      {
         //LOG_SOUND("OpenALChannel isComplete() - never started!");
         complete = true;
      }
      else if (!mDynamicDone)
	  {
         complete = false;
	  }
	  else
	  {
		  // got this hint from
		  // http://www.gamedev.net/topic/410696-openal-how-to-query-if-a-source-sound-is-playing-solved/
		  ALint state;
		  alGetSourcei(mSourceID, AL_SOURCE_STATE, &state);
		  /*
		   Possible values of state
		   AL_INITIAL
		   AL_STOPPED
		   AL_PLAYING
		   AL_PAUSED
		   */
		  if(state == AL_STOPPED)
		  {
			 if (mLoops > 0)
			 {   
				float seek = 0;
				
				if (mStartTime > 0)
				{
				   seek = (mStartTime * 0.001) / mLength;
				}
				
				if (seek < 1)
				{
				   //alSourceQueueBuffers(mSourceID, 1, &inBufferID);
				   alSourcePlay(mSourceID);
				   alSourcef(mSourceID, AL_BYTE_OFFSET, seek * mSize);
				}
				
				mLoops --;
				
				complete = false;
			 }
			 else
			 {
				complete = true;
			 }
			 //LOG_SOUND("OpenALChannel isComplete() returning true");
		  }
		  else
		  {
			 //LOG_SOUND("OpenALChannel isComplete() returning false");
			 complete = false;
		  }
	  }
	  
	  if (complete && mSourceID)
	  {
		 alDeleteSources(1, &mSourceID);
	  }
	  
	  return complete;
   }
```

And [`these two lines`](https://github.com/openfl/openfl/blob/d0f584c91d763384805ee69a8152ac73c4799552/openfl/_legacy/media/SoundChannel.hx#L248-L249) in ` __runCheckComplete ()` to:
```haxe
    stop();
```

@Gama11, @pizzamakesgames (and anyone interested), can you please check if it works on your end too? Still not sure it's the proper fix (but seems more or less how next handles hit too, calling alDeleteSource on channel stop()).

PS: Don't forget to rebuild: `lime rebuild neko -Dlegacy`.

**Comment by pizzamakesgames** [comment] 2015-12-22 14:24
Thank you for all your help! I did try it, and there's a problem suggesting you didn't test the fix for the event of having a continuous sound play while also playing background music, as the music restarts now where it would usually cut out, and it keeps doing so in a couple second long intervals once the point where the sound would usually cut out is reached, also suggesting that this fix doesn't reset the value that is presumably maxing out to it's original value, as it takes way less time to hit upon the point where your fix is triggered once more.

A question I'd have regarding such fixes: What would be a good way to incorporate them in the codebase, so they won't get overwritten every time I'd update lime or neko? Or is that exactly what lime rebuild neko -Dlegacy does?

**Comment by pizzamakesgames** [comment] 2015-12-22 14:48
Okay wait a second, if I disable the music for testing purposes, the continuous sound cuts out as always. Just if I leave the music on while the sound is also playing continuously, the music gets restarted repeatedly once the sound cuts out. The sound still cuts out in both cases.

**Comment by azrafe7** [comment] 2015-12-22 15:22
Mmmhh... Is there any chance you could zip your test project (along with music and sounds) and post it here for us to take a closer look? (oh and specify what libs' versions you're using)

Probably I'll have some time tomorrow to play with it.

I think that once (and if) we find a proper fix for this issue, and it gets reviewed and accepted by the mainteiners, it can safely land in the official codebase.

**Comment by pizzamakesgames** [comment] 2015-12-22 16:19
Very much so!

Here you go: https://www.dropbox.com/sh/of3rekd2bwtk6v4/AADVPU8RCK9B25UGbo-G3TUga

**Comment by azrafe7** [comment] 2015-12-23 09:32
That's a bit too much ;)

Can you please streamline it into a minimal reproducible test project (just background music + typetext)?

**Comment by pizzamakesgames** [comment] 2015-12-23 10:55
Oh, sorry! Well, I spent the last hour trying to reproduce the issue with the FlxTypeText demo, but oddly I havn't been able to. Where in my game project, the background music keeps restarting with the sound cutting out as described, the FlxTypeText demo also has the sound cut out as usual, but the music doesn't cut out or restart.

I've been trying to see what the difference between that project and my game project might be, but had no luck at finding out.

Well, here is the FlxTypeText demo anyway, prepared to type text away forever with music playing in the background: https://www.dropbox.com/s/amzpipndri98ycw/FlxTypeText_Issue962.rar

Maybe if you can find out what the problem with this one is and I can then adjust my own project accordingly.

**Comment by pizzamakesgames** [comment] 2015-12-23 18:03
Getting the same behaviour from testing the FlxTypeText demo on my laptop with this install:
![](http://i.imgur.com/i0gVyL7.png)

**Comment by pizzamakesgames** [comment] 2015-12-23 18:51
Despite FlxTypeText still causing problems, I didn't experience any cutting out with my own game project anymore (sorry took me a while to set it up on the laptop, am abroad). I'll do more long term tests and would still be wondering why the sound is definitely still cutting out for the template project, but for now I can say that I'm not experiencing this issue anymore!

video: https://youtu.be/ABxbgKnR1H4

**Comment by azrafe7** [comment] 2015-12-25 09:31
Aha... try also adding:

```haxe
		 alDeleteSources(1, &mSourceID);
```

in [here](https://github.com/openfl/lime/blob/bc30dc76451ca8355f34751380ef449414b304ec/legacy/project/src/openal/OpenALSound.cpp#L446).

Reason being: when a sound is stopped from the haxe side (stop() in SoundChannel.hx), the handle and the sound instance are set to null. So freeing the source in there makes it reusable.

Don't forget to rebuild.

**Comment by pizzamakesgames** [comment] 2015-12-25 12:08
Pre-emptive question: Do I use the rebuild command for both neko and windows? As far as I remember, people reported the issue to only or mostly persist with the windows target, though you've only stated to rebuild for neko. I've been doing both, pretending to understand what I'm doing. Also, do I need to rebuild once per project from the project folder of each project or just once in general without the need to be in any kind of project folder?

Testing with my game project again, the problem seems fixed. The music isn't restarting anymore at all and the type sfx only cut out in one instance after minutes of constant typing, fixing itself shortly after while the music kept on running throughout.

I've been ignoring the FlxTypeText demo this time, as it still showed no change for some reason, having the sound cut out as usual. Maybe that's because it's forcing the use of some unedited libs or something. Generally I don't know everything that demo is or might be doing, possibly introducing some flaw in the testing process that I'm not aware of.

**Comment by azrafe7** [comment] 2015-12-25 16:10
I think you can use `lime rebuild neko -Dlegacy` and `lime rebuild cpp -Dlegacy` interchangeably, I think (anyone correct me if I'm wrong). What the command does is create the ndll files in the lime/legacy/ndll folder. There's no need to be in any particular folder.

After rebuilding the ndlls you need to recompile your projects though to make them use the modified lib.

How short was the no-sound section before it fixed itself? If it was really short, it's probably dued to the GC kicking in. Otherwise the fix is not working as intended, and some more changes are needed.

I've tested the FlxTypeText too, and it seems to work for me. Try recompiling it with `-clean`, so to ensure that the output is generated from a clean state.

**Comment by pizzamakesgames** [comment] 2015-12-26 23:01
So, I've spend an eternity making ridiculously sure that I'm sporting a 1000% clean install and didn't do a single thing wrong on the way.

haxe 3.2.1
neko 2.0.0
lime 2.8.2
openfl 3.5.3
flixel git dev branch
flixel-addons git dev branch
hxcpp 3.2.193

Made all the changes to the appropriate files of the libs, saved them, rebuild with both commands you posted, downloaded the FlxTypeText from the dropbox link, compiled it with "lime test windows -clean".

Type SFX cut out after about 5 seconds, was still gone after I stopped counting at about 25 seconds. Came right back after de-/refocusing of the game window, only to cut out a couple seconds later, cutting back in another couple seconds later. The background music kept playing throughout.

Testing with my game project, I'm experiencing both the type sfx cutting out and the background music restarting.

...I must be screwing something up, right? I mean, this should be working, shouldn't it?

**Comment by azrafe7** [comment] 2015-12-28 11:55
@pizzamakesgames can you try adding

```haxe
		 mSourceID = 0;
```

after `alDeleteSources(1, &mSourceID);` both in [isComplete()](https://github.com/openfl/lime/blob/bc30dc76451ca8355f34751380ef449414b304ec/legacy/project/src/openal/OpenALSound.cpp#L265) and [stop()](https://github.com/openfl/lime/blob/bc30dc76451ca8355f34751380ef449414b304ec/legacy/project/src/openal/OpenALSound.cpp#L426) (lines 340 and 457 respectively in http://pastebin.com/MssSG7ug)?

**Comment by azrafe7** [comment] 2015-12-28 14:46
Here's what I have compiling it for win (cpp target): https://www.dropbox.com/s/h3q12byun503ye9/skullz2-win-r2.zip?dl=0. Can you please run it and see if it works as expected?

**Comment by pizzamakesgames** [comment] 2015-12-31 17:55
Sorry for taking a bit.

I've added mSourceID = 0; after like 340 and 457 in OpenALSound.cpp and ran the lime rebuild neko -Dlegacy command.

Compiling my project, I still get the type sfx cutting out for a long amount of time rather quickly, with a barrage of the OpenAL error raised lines in the cmd debug window as well as the music restarting frequently.

Testing the project you sent, the only thing I can notice is the music restarting somewhat infrequently, that is only every about 4-8th loop. the type sfx never cuts out, though.

**Comment by pizzamakesgames** [comment] 2016-01-04 21:47
I have a tough time understanding how we could come up with different results, though. Have I been missing any steps? Have you been missing to mention any other changes to the code you did? Would there be other things we could try? I'd be fine with trying out things on my end, I just don't understand the way this all works well enough to look at it on my own.

**Comment by pizzamakesgames** [comment] 2016-01-04 22:28
Here's a possible point of error:

You said to add `alDeleteSources(1, &mSourceID);` at line 446 of OpenALSound.
First, I take it you mean the already edited file from https://github.com/openfl/openfl/issues/962#issuecomment-166589623.
Second, would that mean before or after the highlighted bracket at line 446? https://github.com/openfl/lime/blob/bc30dc76451ca8355f34751380ef449414b304ec/legacy/project/src/openal/OpenALSound.cpp#L446

I've been adding it after, so with the additional line added from the next change, it reads:

```
if (state == AL_PLAYING)
         {
            alSourceStop(mSourceID);
	alDeleteSources(1, &mSourceID);
	mSourceID = 0;
         }
```

**Comment by pizzamakesgames** [comment] 2016-01-04 22:31
Testing again, it took upwards of a minute, so way above 256 sounds, probably at over a thousand before the sound effect cut out and the music subsequently restarting a number of times. I wonder why it's taking so long now?

**Comment by pizzamakesgames** [comment] 2016-01-06 14:23
The issue doesn't happen at all when in fullscreen mode. Is there any quick and easy explanation for that?

**Comment by jonongjs** [comment] 2016-01-17 05:12
@pizzamakesgames I've encountered a similar issue to your original post before, and my solution was essentially the same as @azrafe7's, albeit on an older version of Lime and OpenFL. (For reference, some details of my fix can be found at https://gist.github.com/jonongjs/5dc3ec8848e4bf1f3739).

There was also a similar problem with Shark Punch's "The Masterplan" detailed here: https://groups.google.com/d/msg/haxelang/JZmY830Okm4/Gpch77GITRwJ

As for why the issue doesn't occur at all in fullscreen, one possible explanation could be that there is added memory pressure in that mode (higher resolution, more resources being used, etc) that could cause the garbage collector to kick in more frequently, thereby releasing some OpenAL audio sources for re-use faster.

**Comment by pizzamakesgames** [comment] 2016-09-11 23:46
For anybody experiencing this issue. The only solutions I could find were either forcing fullscreen, as the issue seems not to be present there, or using the next branch of OpenFL, by adding 	<set name="next"/> in the Project.xml of your project, where this issue, and [this one](https://github.com/openfl/openfl/issues/998) do not persist.

**Closed** 2016-12-30 01:45 UTC
