### ISSUE TITLE
GL/Windows: Flixel-ui has upside down rendering

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#597] opened 2015-04-13 18:44 UTC
Can be demonstrated with the current ["User Interface/RPG Interface"](https://github.com/HaxeFlixel/flixel-demos/tree/dev/User%20Interface/RPG%20Interface) demo in Flixel.

Reproduction steps:

1. In [assets/state_title.xml](https://github.com/HaxeFlixel/flixel-demos/blob/dev/User%20Interface/RPG%20Interface/assets/xml/state_title.xml) Comment out the ["radio_group" tag at the bottom of the file](https://github.com/HaxeFlixel/flixel-demos/blob/dev/User%20Interface/RPG%20Interface/assets/xml/state_title.xml#L62). (this bypasses a cast error I will report in another issue)
2. Compile using "lime test neko" (legacy)
3. Compile using "lime test neko -Dnext" (next/standard)

Expectations:

1. Legacy and Next visuals should be quivalent

Results:

1. They are not :)

Legacy:
![rpg_legacy](https://cloud.githubusercontent.com/assets/739064/7122663/8d84fbd8-e1e2-11e4-9df5-acb51d0ecc96.png)

Next:
![rpg_next](https://cloud.githubusercontent.com/assets/739064/7122664/8ff154ca-e1e2-11e4-9a21-80986b1a609d.png)

**Comment by mrcdk** [comment] 2015-04-13 18:49
This has been already fixed on latest git, try it and report back if it hasn't, I'm not having this problem.

**Comment by larsiusprime** [comment] 2015-04-13 18:50
I have the latest git :) It's a subtle, Flixel-UI only error. I reproduced it just now with latest everything.

**Comment by larsiusprime** [comment] 2015-04-13 18:51
Let me post some more infos:

Flixel-UI lets you load scaled images if you put this in the xml:
```
<sprite id="back" src="ui/title_back2" center_x="true" center_y="true" group="title">
    <scale width="100%" height="100%"/>
</sprite>
```

If you just load a standard image, this doesn't happen:
```
<sprite id="back" src="ui/title_back2" center_x="true" center_y="true" group="title">
</sprite>
```

**Comment by larsiusprime** [comment] 2015-04-13 18:55
Okay, more infos!

Loading a scaled image calls this:
https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/FlxUI.hx#L3391

Which calls this:
https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/U.hx#L1064

And then calls this:
https://github.com/HaxeFlixel/flixel-ui/blob/dev/flixel/addons/ui/U.hx#L1091

So a lot of intermediate images might be drawn and stored, so there's a possibility for any internal flipping to become noticeable because of weird interactions with the intermediate caching.

**Comment by mrcdk** [comment] 2015-04-13 19:00
Uh, I still can't reproduce it, I guess this PR is needed? https://github.com/HaxeFlixel/flixel-demos/pull/167

**Comment by larsiusprime** [comment] 2015-04-13 19:02
Yeah, sorry about that. You can pull from the larsiusprime fork.

On Mon, Apr 13, 2015 at 2:00 PM, Justo Delgado <notifications@github.com>
wrote:

> Uh, I still can't reproduce it, I guess this PR is needed?
> HaxeFlixel/flixel-demos#167
> <https://github.com/HaxeFlixel/flixel-demos/pull/167>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openfl/openfl/issues/597#issuecomment-92461450>.
>



-- 
www.fortressofdoors.com -- Games, Art, Design

**Comment by larsiusprime** [comment] 2015-04-13 19:06
Forgot I have push access. Merged.

**Comment by need12648430** [comment] 2015-04-15 07:40
I'm experiencing what appears to be the same bug, outside of Flixel UI.

If I don't call BitmapData.draw, the buffer doesn't get flipped on the Y axis.

I attempted to reproduce it in an isolated environment, but had no luck.

**Comment by larsiusprime** [comment] 2015-04-17 19:05
I'm working on it, I am getting closer:
https://github.com/larsiusprime/openfl/tree/fixupsidedownrender

**Comment by larsiusprime** [comment] 2015-04-17 19:44
PR:
https://github.com/openfl/openfl/pull/607

**Closed** 2015-04-17 20:10 UTC
