### ISSUE TITLE
OpenFL-next does not have "Uncaught Error Event"

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#1054] opened 2016-03-04 05:23 UTC
This must be implemented in order [crashdumper](http://github.com/larsiusprime/crashdumper) to be compatible with OpenFL-next.

If you have a logical place to insert it and/or a rough idea of the implementation, I can take a stab at it myself.

**Comment by ibilon** [comment] 2016-04-23 09:13
Duplicate of #1039 ;)

**Closed by ibilon** 2016-04-23 09:13 UTC
