### ISSUE TITLE
TextField: Characters written in wrong place when you have accent/dieresis + vowels

### ISSUE THREAD

**Issue by aW4KeNiNG** [openfl/openfl#1739] opened 2017-10-21 16:47 UTC
When you write vowels with accent/dieresis, if you press in the text field after these characters, the new characters are written in a wrong place.

The main problem here is the caretIndex has a wrong value. For each vowel with accent before the caret, it sums 2 positions instead of 1. 

Also if you use the left/right cursor on these characters, you need to press twice to move the caret.

Example:

The text:
![image](https://user-images.githubusercontent.com/1063719/31853800-57a48c7a-b68f-11e7-83cc-238dd3c3ebd1.png)

Mouse down:
![image](https://user-images.githubusercontent.com/1063719/31853811-71025dfa-b68f-11e7-8515-29a769bae8f9.png)

Write something:
![image](https://user-images.githubusercontent.com/1063719/31853817-884130fe-b68f-11e7-9b1d-4ef4aeec32fe.png)
![image](https://user-images.githubusercontent.com/1063719/31853819-97081e72-b68f-11e7-8188-ece368e876c8.png)

**Comment by MSGhero** [comment] 2018-01-06 06:09
Does this still happen, and can you see if it happens with other unicode characters? It sounds like a spot where `UTF8String` should be used instead of `String`.

**Comment by vikingx84** [comment] 2018-01-22 06:59
I encountered the same problem, it is reproduced for all Unicode characters, and it concerns only the input spool. UTF8String or normal String does not matter, because the text is displayed correctly, only the input carriage is positioned incorrectly.

Uncertain about this issue, I opened my branch, there is more information.
https://github.com/openfl/openfl/issues/1805
http://community.openfl.org/t/problems-with-entering-non-latin-characters-in-the-input-line-on-android-ios/9964

**Comment by MSGhero** [comment] 2018-01-22 13:27
I’m pretty sure any Unicode issues means UTF strings matter. It looks like `text.length` is being called when text is a normal string, so it’s improperly adding advances. The text layout and the caret position are completely separate.

**Comment by vikingx84** [comment] 2018-01-22 14:02
You are definitely right.
There is a translation problem, so I apologize for the obscurity.
The following remains true: the caret is placed not where I press my finger.
In my tests, I used UTF8String in the line textField.text = "text is everyone there"

**Comment by MSGhero** [comment] 2020-08-01 20:37
This is fixed on dev already.

**Closed by MSGhero** 2020-08-01 20:37 UTC
