### ISSUE TITLE
BitmapData.fillRect doesn't work on mac target

### ISSUE THREAD

**Issue by brokenbeta** [openfl/openfl#1514] opened 2017-02-28 22:01 UTC
haxe 3.4.0
	lime 3.7.4
	openfl 4.8.1

Sample project: https://github.com/brokenbeta/openfl-fillrect

    var s = new Sprite();
    s.graphics.beginFill(0xff0000);
    s.graphics.drawRect(0, 0, 40, 40);
    s.graphics.endFill();

    var bd = new BitmapData(200, 200, true, 0xffc0c0c0); // outer grey square
    bd.fillRect(new Rectangle(100, 0, 40, 40), 0xffffff00); // small yellow square
    bd.draw(s); // small red square
    addChild(new Bitmap(bd));

So as far as I can tell, on flash, windows, html5 targets, all three squares appear in the BitmapData.

But on mac:

- the grey square is missing (should be made by BitmapData constructor)
- the yellow square is also missing (should be filled by fillRect invocation)
- only the red square appears

**Comment by brokenbeta** [comment] 2017-03-01 14:26
When running `haxelib run lime test flash`: (this is how it should be)

![fillrect_flash](https://cloud.githubusercontent.com/assets/3834867/23463863/fc6f241c-fe8a-11e6-8770-a37434da746e.png)

When running `haxelib run lime test mac`:

![fillrect_mac](https://cloud.githubusercontent.com/assets/3834867/23463873/06ad8ce8-fe8b-11e6-9642-3a67055ba868.png)

Note that the grey and yellow squares are missing.

**Comment by wildfireheart** [comment] 2017-03-01 21:27
I confirm this issue, probably caused by some recent underlaying changes?

**Comment by jgranick** [comment] 2017-03-08 04:16
It doesn't make sense that's its Mac only, unless it's Haxe 3.4 related somehow. I'll try and test on a Mac here and see what comes up

**Comment by justin-espedal** [comment] 2017-03-08 18:05
I was running into this issue on Windows as well. In my case it was fixed by updating to the latest Haxe nightly build.

**Comment by jgranick** [comment] 2017-03-08 18:33
Still waiting for Haxe 3.4 to stabilize 😅 

http://community.openfl.org/t/poll-haxe-3-4-0-testing/8778

**Closed** 2017-03-08 18:32 UTC

**Comment by brokenbeta** [comment] 2017-03-08 18:34
I can't speak for the nightly build, but the <haxedef /> seems to work, so I'm happy :)
