### ISSUE TITLE
Missing "Default-568h@2x.png" launch image

### ISSUE THREAD

**Issue by grapefrukt** [openfl/openfl#463] opened 2015-01-08 10:55 UTC
![mac os x 10 9-2015-01-08-11-52-49](https://cloud.githubusercontent.com/assets/158901/5661520/0ce41cca-972d-11e4-91b1-11f1cd3b7ccd.png)

This [old bug](https://github.com/openfl/openfl-native/issues/11) is still alive and kicking. I just tried this on a clean install of haxe (3.1.3), openfl (2.2.1) and xcode (6.1.1) using a project with no launch images defined in the project. 
The XCode project generated by `openfl update ios` somehow messes up the reference to the `Default-568h@2x.png`file, as it *is* included in the project but only as a file and not as an actual launch image.

**Comment by jgranick** [comment] 2015-01-08 18:48
I believe this was either a bug in Xcode (when not using an asset catalog) or a missing entry in the Info.plist, though documentation on what tags were needed eluded my searches across the internet.

I migrated the project template to use an Xcode asset catalog, hopefully this doesn't hurt support on older Xcode releases. It seems to be much happier, and the way it is intended to be done now.

I also fixed one of the recommended changes, the only thing that's still is in the target architecture being hard-coded. I'm not sure that we should allow Xcode to choose it automatically, as that's what the architecture settings in the project files are for.

**Comment by jgranick** [comment] 2015-01-08 18:48
Here's the relevant commit https://github.com/openfl/lime/commit/af5396119e3d511d2c9713e0aa56f34b332baa64 :smile:

**Comment by jgranick** [comment] 2015-01-08 21:14
I just reverted the ONLY_TARGET_ARCH change, as it broke the builds (it wouldn't show any "eligible" target devices) and fixed a problem that affected command-line compiling. I think it's good now (if you ignore the "recommended setting" message) but I'm happy to hear feedback on how it's working out

**Comment by grapefrukt** [comment] 2015-01-08 23:09
I just tried this and the original warning when the project is generated is indeed gone. The images also seem to be included in the asset catalogs properly, however, I get these warnings once I compile the game:
![mac os x 10 10 yosemite -2015-01-09-00-01-15](https://cloud.githubusercontent.com/assets/158901/5672679/0a9f23b8-9793-11e4-8439-c6c9f40906ae.png)

I'll try and look into this tomorrow, I'm not quite sure how many of the images it picks up (the game icon is still properly displayed).

**Comment by jgranick** [comment] 2015-01-08 23:36
Try it now, the JSON files should be copying as intended after my last fix

**Closed** 2015-01-09 17:06 UTC
