### ISSUE TITLE
Blend Mode ADD too bright

### ISSUE THREAD

**Issue by mikeevmm** [openfl/openfl#1077] opened 2016-03-31 09:24 UTC
From HaxeFlixel repository:
- **Flixel version:** 4.0.1
- **OpenFL version:** 3.6.0
- **Lime version:** 2.9.0
- **Affected targets:** Windows, Neko (Presumably mac?)

---

**Code snippet reproducing the issue**:

``` haxe
package;

import flixel.FlxState;
import flixel.FlxSprite;
import openfl.display.BlendMode;

class PlayState extends FlxState
{
    override public function create():Void
    {
        add(new FlxSprite(0, 0, "bg.png"));
        var layer:FlxSprite = new FlxSprite(0, 0, "addLayer.png");
        layer.blend = BlendMode.ADD;
        add(layer);
    }
}
```

**bg.png:**
![parallax_20160331_131939](https://cloud.githubusercontent.com/assets/7550678/14175512/5556f88e-f743-11e5-95fe-30e1cf0cc9a9.jpg)

**addlayer.png:**
![layer 3 add_20160331_131951](https://cloud.githubusercontent.com/assets/7550678/14175528/6993d06a-f743-11e5-98c6-50ca6614ba7e.jpg)

---

**Observed behavior:** 

![](https://lh3.googleusercontent.com/-LS2pv8bXQG8/Vvh9rJn6OJI/AAAAAAAAB5Q/2saGdai-mYIHbFh0t9IPAiJAEXOrv38vQ/s1600/Capture.PNG)

**Expected behavior:**

![](https://lh3.googleusercontent.com/-XLK1-KnA4ME/Vvh-i5kutCI/AAAAAAAAB5Y/gGwqMB9SiEYFhwesWuBIo2OPVpP87PAFA/s1600/Capture.PNG)

According to @Gama11:

> Flixel just passes whatever blend mode a sprite has on to OpenFL's drawTiles API, so there's not much we can do about it. This can very likely be reproduced using only OpenFL.

**Comment by Gama11** [comment] 2016-03-31 09:43
Btw, to properly reproduce this, the original image is needed as well.

**Comment by mikeevmm** [comment] 2016-03-31 12:08
@Gama11 As in, the add layer without the blend?

**Comment by Gama11** [comment] 2016-03-31 12:08
Yes. How are you supposed to run the code otherwise? :)

**Comment by ashes999** [comment] 2016-04-02 21:35
@mikeevmm your art style is pretty awesome. Can you explain why you're using the add layer like this? (Why not just generate the image in GIMP/etc. with the add layer?)

**Comment by larsiusprime** [comment] 2016-04-02 21:43
@ashes999 dynamic effects is one use case (varying partially transparent overlay w/ blending)

**Comment by mikeevmm** [comment] 2016-04-02 23:50
@ashes999 Thank you, but I'm just the programmer :(

@larsiusprime is spot on.

**Comment by azrafe7** [comment] 2016-04-15 02:24
Hey @mikeevmm, I tried to replicate this but haven't been able to (in the sense that both neko and flash gave the same output - or so it seemed). As a side note, github seems to have autoconverted the above layer.png into a jpeg, so losing the alpha values (although I've also tested it by making it a png with white being transparent). 

If you can please post a complete project I'm willing to look into it a bit more, can you?

Also: does something change if you use `lime test neko --window-hardware=false`?

**Comment by mikeevmm** [comment] 2016-04-20 10:08
I'm sorry I've taken so long to reply; school got in the way -- I'll send a complete project asap.

Disabling hardware made the game unbearably slow.

**Comment by mikeevmm** [comment] 2016-04-22 09:25
@azrafe7 Mind if I send you the project privately/through PM or email? I'm working with a team, so I'm not sure whether disclosing art/etc is okay.

**Comment by azrafe7** [comment] 2016-04-22 19:15
@mikeevmm, I'd suggest replacing the art files with temp ones (f.e. from [here](http://lpc.opengameart.org/)), and post the minimal project publicly so that others can help/take a look at it. (Also, using different assets might also exclude the hypothesis that the problem has to do with incorrect formats).

On the other hand, I'd be glad to take a look at what you have right now (if you feel so inclined). Of course no guarantee I'll be able to find a solution ;)

**Comment by mikeevmm** [comment] 2016-04-22 23:47
Done! https://github.com/mikeevmm/flixel-add-blend-test

**Comment by azrafe7** [comment] 2016-04-23 23:17
Ok, this is not a final answer, but here's what I've found so far:
 - code involving blendmodes in _legacy_ is [here](https://github.com/openfl/lime/blob/9d95964f2f20136540b3ec6145f7cac6f6ae802b/legacy/project/src/opengl/OpenGLContext.cpp#L480)
 - for what I could gather it's not possible to _exactly_ replicate `MULTIPLY` using `glBlendFunc()` (see [this post](http://gamedev.stackexchange.com/questions/17043/blend-modes-in-cocos2d-with-glblendfunc)), but the current implementation is a fair enough approximation of it
 - it could be possible to faithfully replicate it by using a shader

As I said, not a final answer (I'll probably tink more with it tomorrow). In the meantime I'd hope to be successful in summoning @mrcdk (sorry to bother you) - who seems quite knowledgeable about the matter at hand - and see what his opinion is about this.

Worth noting is that the `ADD` blendmode behaves in a very similar way in both flash and neko, while `MULTIPLY` is much more different.

(f.e.: this is a diff made with imagemagick `compare` command between flash and neko, using only `ADD` (no `MULTIPLY`), with a fuzz factor of 5%):
![diff-add-flashvsneko-5p](https://cloud.githubusercontent.com/assets/1266447/14764479/8adc3c8e-09b9-11e6-90a6-26f161263c3b.png)

Also, it seems that blendmodes work correctly with openfl next (anyone correct me if I'm wrong here).

**Comment by azrafe7** [comment] 2016-04-25 21:41
Hey @mikeevmm, can you please test the [pure-openfl branch here](https://github.com/azrafe7/flixel-add-blend-test/tree/pure-openfl) and report what you see by running `lime test openfl-project neko -Dlegacy`? 

I've added 2 screenshots in there that show what I see on my laptop, and was surprised to see that they are very similar (as opposed to what I experienced by running the flixel test).

Don't feel to exclude that I'm doing something different on my end though (I've rebuilt lime ndll quite a few times lately).

**Comment by azrafe7** [comment] 2016-04-25 22:10
(I'm starting to suspect that there's something weird with TileSheet, not sure on what side - my code?, openfl?, flixel?)

**Comment by azrafe7** [comment] 2016-04-26 23:44
@mikeevmm Maybe I've found a solution... \o/

Not an official fix as this could break something else, but the results are encouraging (and hope someone more knowledgeable than me will chime in to comment).

For what I could gather it has to do with premultipliedAlpha and BlendMode.MULTIPLY.
Might be wrong, but it seems that `glBlendFunc(GL_DST_COLOR, GL_ONE_MINUS_SRC_ALPHA)` works _correctly_ only if the supplied texture-to-be-multiplied-with is in premultiplied alpha format.
(curious about the possibility of using glBlendSeparateFunc, feasible??)

Probably the fix could be applied directly to OpenGLContext.cpp, or legacy openfl (haven't tried honestly - and don't forget that this is _legacy_!).
In the meanwhile please test [this repo](https://github.com/azrafe7/flixel-add-blend-test/tree/master) and report back.

**Comment by mikeevmm** [comment] 2016-04-27 10:49
@azrafe7 thank you! \o/

Will test ASAP

**Comment by mikeevmm** [comment] 2016-04-30 16:36
@azrafe7 Have tested the master branch of your fork; everything looks fine, both on lime and windows:

**flash:**
![image](https://cloud.githubusercontent.com/assets/7550678/14937256/e2e76a9e-0ef9-11e6-88c9-ea9295bc95b4.png)


**lime:**
![image](https://cloud.githubusercontent.com/assets/7550678/14937247/a5e77968-0ef9-11e6-82b2-c66e8a6971e2.png)


**windows:**
![image](https://cloud.githubusercontent.com/assets/7550678/14937245/829b05ba-0ef9-11e6-8a9f-a5afd384d895.png)


:+1: :+1: :+1:

**Comment by azrafe7** [comment] 2016-04-30 18:20
Great! :+1:

**Comment by mikeevmm** [comment] 2016-05-07 17:39
@Gama11 Perhaps this could be temporarily fixed in HaxeFlixel by setting premultiplied alpha to true if blendMode = MULTIPLY and cpp?

**Comment by Gama11** [comment] 2016-05-09 13:05
I'd rather not, that sounds like a pretty nasty hack. Who knows what side-effects enabling premultiplied alpha could have...

**Comment by mikeevmm** [comment] 2016-06-06 19:42
Just a note: with flixel 4, `setPremultipliedAlpha` seems to be gone.

**Comment by Gama11** [comment] 2016-06-06 19:43
You mean OpenFL 4?

**Comment by mikeevmm** [comment] 2016-06-06 19:45
Ah, yes, sorry.

**Comment by Gama11** [comment] 2016-06-06 19:55
Probably a side effect of it only exisiting in OpenFL legacy, and legacy having been removed?

**Comment by mikeevmm** [comment] 2016-06-06 22:47
Legacy has been removed? `#if next` still yields different results with and without `-Dnext`

**Comment by jgranick** [comment] 2016-06-06 23:46
It depends on whether you are using a `development` branch, or haxelib

**Comment by jgranick** [comment] 2016-06-06 23:48
The core difference is that old code used non-premultiplied alpha, the new code has premultiplied alpha in textures

This changes how blend modes behave, if you guys have suggestions, I'd be happy to look at moving to blend modes that match the GL blend functions appropriate for premultiplied alpha

Thanks

**Comment by mikeevmm** [comment] 2016-06-07 10:27
@jgranick Ah, I'm a bit out of my league here...

**Comment by jgranick** [comment] 2017-01-04 21:32
I am closing this issue, because it no longer applies to current OpenFL/Lime releases (very different codebase), but I am also tracking here:

https://github.com/openfl/openfl/issues/1414

In general, we need to look at our blend mode support across GL, canvas and Cairo, and visit what we can reliably support out-of-the-box, and what we should consider making up with filters

Thank you

**Closed by jgranick** 2017-01-04 21:32 UTC
