### ISSUE TITLE
drawTriangles() and/or beginBitmapFill issues on html5 & neko

### ISSUE THREAD

**Issue by scanline** [openfl/openfl#1261] opened 2016-09-07 10:58 UTC
If I target flash using OpenFL 3.6.1 - Lime 2.9.1 or OpenFL 4.0.1 - Lime 3.1.0 I get
the desired output:
![flash](https://cloud.githubusercontent.com/assets/22029272/18309307/044dae68-74f9-11e6-84f0-d78381ddac14.png)

If targeting Neko, it looks a little different:
![neko](https://cloud.githubusercontent.com/assets/22029272/18309351/349b080e-74f9-11e6-8594-843b3629d66c.png)

Obviously it's clipping the shape, which might be related to this:
http://community.openfl.org/t/bug-graphics-drawtriangles-if-targeting-html5/8029

On html5 -Dwebgl it's even worse!
Using OpenFL 3.6.1 - Lime 2.9.1:
![html5](https://cloud.githubusercontent.com/assets/22029272/18309424/aac33a4c-74f9-11e6-81e0-c95ce01c7ab2.png)

Using OpenFL 4.0.1 - Lime 3.1.0 there's nothing to be seen at all!

Additionally, Matrix3D.appendTranslation() seems to give different results based on the target.
To make the shape look equal in size I had to use appendTranslation(0,0,100) on flash vs.
appendTranslation(0,0,400) on the other targets.

Here's the complete code for better investigation:

```haxe
package;

import openfl.display.Sprite;
import openfl.display.BitmapData;
import openfl.display.Bitmap;
import openfl.display.Graphics;
import openfl.display.TriangleCulling;
import openfl.Lib;
import openfl.geom.*;
import openfl.Vector;
import openfl.events.Event;

class Main extends Sprite 
{ 
    private var mat:Matrix3D = new Matrix3D();
    private var vertices:Vector<Float>=Vector.ofArray([-20, -20, 0, 20, -20, 0, 20, 20, 0, -20, 20, 0]);
    private var uvt:Vector<Float>=Vector.ofArray([0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0]);
    private var indices:Vector<Int>=Vector.ofArray([0, 1, 3, 1, 2, 3]);     
    private var projectedPoints:Vector<Float>;
    private var plane:Sprite = new Sprite();
    private var pProjection:PerspectiveProjection = new PerspectiveProjection();
    private var dX:Float = 0;
    private var dY:Float = 0;
    private var proj:Matrix3D;
    private var texture:BitmapData;

    public function new() 
    {
        super();
        projectedPoints = new Vector<Float>(Math.ceil(vertices.length / 3 * 2));
        addChild(plane);
        plane.x = stage.stageWidth / 2;
        plane.y = stage.stageHeight / 2;
        var color1:Int = 0xffffff;
        var color2:Int = 0x000000;
        var lastColor:Int = color1;
        var clipRect:Rectangle = new Rectangle(0, 0, 8, 8);
        texture = new BitmapData(256, 256, false, 0x000000);

        for (y in 0...32)
        {
            for (x in 0...32)
            {
                clipRect.y = y * 8;
                clipRect.x = x * 8;
                texture.fillRect(clipRect, lastColor);

                lastColor = (lastColor == color1) ? color2 : color1;
                if (x + 1 == 32 && x % 2 != 0)
                lastColor = (lastColor == color1) ? color2 : color1;
            }
        }

        pProjection.fieldOfView = 45;
        proj = pProjection.toMatrix3D();    

        addEventListener(Event.ENTER_FRAME, loop);
    }

    private function loop(e:Event):Void
    {
        dX += (mouseX - dX) / 4;
        dY += (mouseY - dY) / 4;
        mat.identity();
        mat.appendRotation(dX, Vector3D.X_AXIS);
        mat.appendRotation(dY, Vector3D.Y_AXIS);
        mat.appendTranslation(0, 0, 100);
        mat.append(proj);    
        projectedPoints = new Vector<Float>();
        Utils3D.projectVectors(mat, vertices, projectedPoints, uvt);

        plane.graphics.clear();
        plane.graphics.lineStyle(1, 0xff0000);
        plane.graphics.beginBitmapFill(texture, null, false, false);
        plane.graphics.drawTriangles(projectedPoints, indices, uvt, TriangleCulling.NONE);
        plane.graphics.endFill(); 
    }    
}
```

**Comment by RblSb** [comment] 2017-06-06 03:16
The difference between html5 and neko is no more, but the problem with bitmapdata remains.
Corrected an example for compilation:
https://gist.github.com/RblSb/25a47c7f9b2bbfe19168e3147b117436
Related to #1214

**Comment by jgranick** [comment] 2018-03-16 21:36
Thanks for the great sample! This is fixed :smile:

_The Cairo/canvas render path does need to support the "T" value from `uvtData` in order to correct the perspective, but I'm closing this topic because the issue is fixed_

**Closed by jgranick** 2018-03-16 21:36 UTC
