### ISSUE TITLE
Cannot use git as version in haxelib.json dependencies

### ISSUE THREAD

**Issue by CrazyFlasher** [openfl/openfl#2288] opened 2019-10-31 14:53 UTC
Hi.
I created private git repository with haxelib.json
When I run:
`haxelib git casinohx https://bitbucket.org/Ganalogics/casinohx.git develop --always`
it successfully installs casinohx lib with its dependencies.
But when I run
`haxelib run openfl build ProjectWeb.xml html5 -release -Dwebgl --no-traces -verbose`

I receive error:
```
Error:Could not find haxelib "casinohx", does it need to be installed?
```
Why? Lib is installed and located on disk

UPD:
When I run:
`haxelib path casinohx`

I get
```Error: Cannot process [casinohx]: git:https://github.com/BowlerHatLLC/feathersui-openfl.git#7563bda05cefd736bc1e3f0a6bc6fadff68c0efa is not a valid version string```

In haxelib.json I have strict vesions:
```
"dependencies": {
    "feathersui": "git:https://github.com/BowlerHatLLC/feathersui-openfl.git#7563bda05cefd736bc1e3f0a6bc6fadff68c0efa",
    "spritesheet": "git:https://github.com/CrazyFlasher/spritesheet.git#f0b1dcec93afec6729b2c9cc108a12f9c2d9cfd8",
    "zame-particles": "git:https://github.com/restorer/zame-haxe-particles.git#c6163c797395587186df5aeb1121c8ea98c5ea4e",
    "spine-hx": "git:https://github.com/jeremyfa/spine-hx.git#365b6ca77e33d0f3a9417ea8d8466b5a8be23c9c",
    "openfl-spine": "git:https://github.com/rainyt/openfl-spine.git#2a40997bb56c9492502f66c375b95b9b78040afb",
    "DomWires": "1.0.0-alpha.5",
    "format": "git:https://github.com/HaxeFoundation/format.git#d01b01c40a95b2a5aae65e6e39e4e08fbee01436"
  }
```

**Comment by RealyUniqueName** [comment] 2019-10-31 17:06
That's probably related to the latest changes in haxelib after Haxe 4.0.0-rc.5 was released. Does it work with haxelib bundled into 4.0.0-rc.5?

**Comment by CrazyFlasher** [comment] 2019-10-31 17:33
Yes, it works with 4.0.0-rc.5

**Comment by Gama11** [comment] 2019-10-31 17:36
This seems to be a duplicate of https://github.com/HaxeFoundation/haxelib/issues/476, and is not really related to OpenFL.

**Closed by Gama11** 2019-10-31 17:36 UTC
