### ISSUE TITLE
BitmapData.copyPixels() alphaBitmapData

### ISSUE THREAD

**Issue by adrianulima** [openfl/openfl#910] opened 2015-10-29 15:01 UTC
I'm having some problems with `BitmapData.copyPixels()`, I don't know if I'm doing something wrong, but the `alphaBitmapData` is only working for flash target.

![bitmapdatacopyalphabug](https://cloud.githubusercontent.com/assets/13324869/10822027/5d78015a-7e3c-11e5-8e70-b2ff2f612f35.gif)

I talked to @larsiusprime.
Seems like it's not interpreting the alpha channel correctly.

``` haxe
var obj1:Sprite = new Sprite();
obj1.graphics.beginFill(0xff0000);
obj1.graphics.drawCircle(50, 50, 50);
obj1.graphics.endFill();
obj1.x = 180;
obj1.y = 200;
addChild(obj1);

var obj2:Sprite = new Sprite();
obj2.graphics.beginFill(0xffff00);
obj2.graphics.drawRect(0, 0, 100, 100);
obj2.graphics.endFill();
obj2.x = 300;
obj2.y = 200;
addChild(obj2);

var bmp1:BitmapData = new BitmapData(cast obj1.width, cast obj1.height, true, 0x00000000);
bmp1.draw(obj1);
var bmp2:BitmapData = new BitmapData(cast obj2.width, cast obj2.height, true, 0x00000000);
bmp2.draw(obj2);

// ---Look here---
var bitmapData = new BitmapData(cast bmp2.width, cast bmp2.height, true, 0x00000000);
bitmapData.copyPixels(bmp2, bmp2.rect, new Point(), bmp1, null, true);
// ---------------

var obj3:Bitmap = new Bitmap(bitmapData);
obj3.x = 420;
obj3.y = 200;
addChild(obj3);
```

**Comment by jgranick** [comment] 2015-10-29 17:35
I just fixed a crash that was caused by the null alpha point, now native looks similar to HTML5, so something is a little funny.

If someone has time, you can add `false && ` to the `CFFI.enabled` check here, and use the Haxe copy of the copyPixels logic to figure this one out:

https://github.com/openfl/lime/blob/master/lime/graphics/utils/ImageDataUtil.hx#L159

It's the last piece of logic, where `alphaImage != null`

**Comment by azrafe7** [comment] 2015-11-12 00:57
Changing the order of conditionals in https://github.com/openfl/lime/blob/0d0c04abad0831d5572e1e360d91a8558a111a6c/lime/graphics/utils/ImageCanvasUtil.hx#L93 seems to make it work for *html5/canvas*, so maybe it's a start ;).

```haxe
public static function copyPixels (image:Image, sourceImage:Image, sourceRect:Rectangle, destPoint:Vector2, alphaImage:Image = null, alphaPoint:Vector2 = null, mergeAlpha:Bool = false):Void {
	
	if (destPoint == null || destPoint.x >= image.width || destPoint.y >= image.height || sourceRect == null || sourceRect.width < 1 || sourceRect.height < 1) {
		
		return;
		
	}
	
	sync (image, true);
	
	if (!mergeAlpha) {
		
		if (image.transparent && sourceImage.transparent) {
			
			image.buffer.__srcContext.clearRect (destPoint.x + image.offsetX, destPoint.y + image.offsetY, sourceRect.width + image.offsetX, sourceRect.height + image.offsetY);
			
		}
		
	}
	
	sync (sourceImage, false);
	
	if (sourceImage.buffer.src != null) {
		
		image.buffer.__srcContext.drawImage (sourceImage.buffer.src, Std.int (sourceRect.x + sourceImage.offsetX), Std.int (sourceRect.y + sourceImage.offsetY), Std.int (sourceRect.width), Std.int (sourceRect.height), Std.int (destPoint.x + image.offsetX), Std.int (destPoint.y + image.offsetY), Std.int (sourceRect.width), Std.int (sourceRect.height));
		
	}
	
	if (alphaImage != null && alphaImage.transparent) {
		
		if (alphaPoint == null) alphaPoint = new Vector2 ();
		
		image.copyChannel (alphaImage, new Rectangle (alphaPoint.x, alphaPoint.y, sourceRect.width, sourceRect.height), new Vector2 (sourceRect.x, sourceRect.y), ImageChannel.ALPHA, ImageChannel.ALPHA);
		
	}
	
}
```

Anyway it seems to be quite a hairy problem to make it behave the same as Flash for all targets, with all the possible parameters (AS3 docs aren't much helpful in this case). The best path - maybe - would be to write down a bunch of edge cases and try to find out how to comply with Flash behaviour (not very nice as there are 6/7 parameters to test for various combinations, and I still don't know if `mergeAlpha` is dependent on `alphaBitmap` or not, f.e.).

Still looking into it though... I'll report back if I found a sound solution.

**Comment by azrafe7** [comment] 2015-11-12 23:17
Here's (https://github.com/openfl/lime/blob/0d0c04abad0831d5572e1e360d91a8558a111a6c/lime/graphics/utils/ImageDataUtil.hx#L288) missing an `alphaPosition += 4;`. Neko is coming along but I'm not quite there yet.

**Comment by azrafe7** [comment] 2015-11-15 00:00
**UPDATE**: I made some progress with this...

Please test this further!

I'm simulating how copyPixels works in flash with a custom implementation, and by now all the tests are behaving the same in flash/neko/html5 (it's not improbable that I might be missing some edge cases though ;).

The (pseudo)code is something like this: 

```haxe
function copyPixels(destImage:BitmapData, sourceImage:BitmapData, sourceRect:Rectangle, destPoint:Point, alphaImage:BitmapData = null, alphaPoint:Point = null, mergeAlpha:Bool = false):Void {
	var sourcePixels = Pixels.fromBitmapData(sourceImage);
	var destPixels = Pixels.fromBitmapData(destImage);
	var alphaPixels = alphaImage != null ? Pixels.fromBitmapData(alphaImage) : null;
	
	for (y in 0...sourceImage.height) {
		for (x in 0...sourceImage.width) {
			var sourcePixel = sourcePixels.getPixel32(x, y);
			var destAlpha = sourcePixel.A;
			if (alphaImage != null) destAlpha = Math.floor(alphaPixels.getPixel32(x, y).A * sourcePixel.A / 0xFF);
			var destPixel:Pixel = sourcePixel;
			destPixel.A = destAlpha;
			if (x == 2 && y == RADIUS) trace(StringTools.hex(sourcePixel, 8), StringTools.hex(destAlpha, 2), StringTools.hex(destPixel));
			destPixels.setPixel32(x, y, destPixel);
		}
	}
	
	destPixels.applyToBitmapData(destImage);
}
```

It seems that the `mergeAlpha` param is redundant if `alphaImage` is not null.

What needs to be done now is to convert this to use OpenFL classes, and take care of rects and points (along with un/multiplied alpha!).

(gist is [here](https://gist.github.com/azrafe7/85e3cf486ffe23b13102))

**Comment by azrafe7** [comment] 2015-11-15 00:03
@jgranick can you help me with integrating this into openfl/lime (if you find it sound enough)?

**Comment by MSGhero** [comment] 2015-11-15 00:13
Can you compare the speeds of this and flash's native `copyPixels`? copyPx is one of the fastest functions in as3 given what it does, and you may be missing important optimizations in this implementation.

I just realized I haven't used the `alphaBMD` parameter in my four years of coding for flash. I've set `mergeAlpha` to false less than 10 times.

**Comment by azrafe7** [comment] 2015-11-15 01:41
@MSGhero: yep, I'll try to benchmark it! Will report back as soon as I have something.

**Comment by azrafe7** [comment] 2015-11-15 23:53
And here's a step back :/

... I've run my implementation through more tests only to find out that I get many cases wrong wrt native flash. Specifically I don't understand how `mergeAlpha` works in flash. I've found this post (http://www.designswan.com/archives/the-function-of-mergealpha-in-copypixels.html) that hopefully gets flash's inner workings right, but no significant progress so far.

As of now I'm just trying to simulate the flash behaviour with a custom function. When that is done we could look at how to optimize it. Any suggestions very welcome!

**Comment by azrafe7** [comment] 2015-11-16 00:46
This is the updated gist with the new tests: https://gist.github.com/azrafe7/85e3cf486ffe23b13102

 - press SPACE to toggle between openfl and "simulated" copypixels
 - use the flash target to see how it should behave

**Comment by azrafe7** [comment] 2015-11-18 23:06
I think I got it at last ;)

Here's the relevant functions (not accounting for rects and offsets yet):

```haxe
inline function fclamp(val:Float):Int {
	return val <= 0 ? 0 : val >= 0xFF ? 0xFF : Math.floor(val);
}

function blend(srcPixel:Pixel, dstPixel:Pixel):Pixel {
	var res:Pixel = 0;
	var srcA = srcPixel.A / 0xFF;
	var dstA = dstPixel.A / 0xFF;
	var outA = srcA + dstA * (1 - srcA);
	var invOutA = 1 / outA;
	if (outA == 0) {
		res = 0;
	} else {
		res.R = fclamp(invOutA * ((srcPixel.R * srcA + dstPixel.R * dstA * (1 - srcA))));
		res.G = fclamp(invOutA * ((srcPixel.G * srcA + dstPixel.G * dstA * (1 - srcA))));
		res.B = fclamp(invOutA * ((srcPixel.B * srcA + dstPixel.B * dstA * (1 - srcA))));
		res.A = Std.int(outA * 0xFF);
	}
	return res;
}

function copyPixels2(destImage:BitmapData, sourceImage:BitmapData, sourceRect:Rectangle, destPoint:Point, alphaImage:BitmapData = null, alphaPoint:Point = null, mergeAlpha:Bool = false):Void {
	
	sourceRect = sourceImage.rect;
	destPoint = new Point();
	alphaPoint = new Point();
	
	var sourcePixels = Pixels.fromBitmapData(sourceImage);
	var destPixels = Pixels.fromBitmapData(destImage);
	var alphaPixels = alphaImage != null ? Pixels.fromBitmapData(alphaImage) : null;
	
	for (y in 0...sourceImage.height) {
		for (x in 0...sourceImage.width) {
			var sourcePixel = sourcePixels.getPixel32(x, y);
			var destPixel = destPixels.getPixel32(x, y);
			var resPixel = sourcePixel;
			if (alphaPixels != null) {
				var alphaPixel = alphaPixels.getPixel32(x, y);
				var srcMultAlphaPixel = sourcePixel;
				srcMultAlphaPixel.A = Std.int(sourcePixel.A * alphaPixel.A / 0xFF);
				if (alphaImage.transparent && (mergeAlpha || !destImage.transparent)) {
					resPixel = blend(srcMultAlphaPixel, destPixel);
				} else {
					resPixel = srcMultAlphaPixel;
				}
			}
			destPixels.setPixel32(x, y, resPixel);
		}
	}
	
	destPixels.applyToBitmapData(destImage);
}
```

Results from my tests are 99% equal to flash (there's an occational off-by-one value in the output pixel values - not sure where it's coming from).

One thing I noticed is that on neko/cpp the fill color specified when you create a BitmapData doesn't respect the alpha value (I'll post an issues about that later), but works fine on html5.

Next I'm going to convert this to use openfl internals, add missing logic for rects and offsets, and then we could look into how to optimize it.

(I've updated the gist, but it's grown into quite a messy thing ;)

**Comment by azrafe7** [comment] 2015-11-19 00:28
@MSGhero, I think resolving this would require only some minor changes to your implementation.

Apart from incrementing the `alphaPosition` probably one of the things needed (possibly the only one?!) is to multiply the alpha with source and use the result before blending it with dest. Can you help me out with this?

**Comment by azrafe7** [comment] 2015-11-23 02:38
Playing a bit more with this. Here's what seems to work:

```haxe
	/** No checks and not accounting for rects/offsets. */
	function copyPixels2(destImage:BitmapData, sourceImage:BitmapData, sourceRect:Rectangle, destPoint:Point, alphaImage:BitmapData = null, alphaPoint:Point = null, mergeAlpha:Bool = false):Void {
		
		var needsMultiplyAlpha = alphaImage != null && alphaImage.transparent;
		var needsBlending = mergeAlpha || (needsMultiplyAlpha && !destImage.transparent);
		
		var sourcePixels = Pixels.fromBitmapData(sourceImage);
		var destPixels = Pixels.fromBitmapData(destImage);
		
		var sourcePixel, destPixel, resPixel;
		var alphaPixels, alphaPixel;
		
		if (needsMultiplyAlpha) alphaPixels = Pixels.fromBitmapData(alphaImage);
		
		for (y in 0...sourceImage.height) {
			for (x in 0...sourceImage.width) {
				sourcePixel = sourcePixels.getPixel32(x, y);
				destPixel = destPixels.getPixel32(x, y);
				
				if (needsMultiplyAlpha) {
					alphaPixel = alphaPixels.getPixel32(x, y);
					sourcePixel.A = Std.int(sourcePixel.A * alphaPixel.A / 0xFF);
				}
				
				resPixel = sourcePixel;
				
				if (needsBlending) resPixel = blend(sourcePixel, destPixel);
				
				destPixels.setPixel32(x, y, resPixel);
			}
		}
		
		destPixels.applyToBitmapData(destImage);
	}
```

Neko shows the same behaviour as flash now. 

In my poor efforts to optimize it I've tried to organize the conditionals and move the var declarations outside, but not much was gained with that. Benchmarking it with neko still seems to be one order of magnitude behind flash (remember I've disable cffi though!).

Help would be appreciated to solve this, although I'm aware only a few ones are using the more _exotic_ parameters of copyPixels().

**Comment by larsiusprime** [comment] 2015-11-23 04:24
I remember messing with this back in the early days of OpenFL / NME implementing BitmapData.threshold(), and for something like this you're going to run into an optimization wall unless you pull the logic down into the c++ level and directly manipulate stuff there.

Great work nonetheless! Logic first, performance afterwards.

**Comment by jgranick** [comment] 2017-06-02 19:24
I'm embarrassed about the time delay, but I have had the chance to work with your thorough sample, and work your optimizations into Lime to resolve this issue. It now behaves properly on HTML5, and (I believe) behaves as well as possible on native with premultiplied `BitmapData`.

We should (perhaps) consider inspecting when `BitmapData` becomes premultiplied, and defer it only until generating an OpenGL texture, if we do not already

**Closed by jgranick** 2017-06-02 19:24 UTC
