### ISSUE TITLE
[HTML5] Textfield Bugs

### ISSUE THREAD

**Issue by aravinthsundaram** [openfl/openfl#2000] opened 2018-09-06 04:46 UTC
Manipulating Textfield with filters are broken with Openfl 8.4.1
eg.,
Scale in scale out text on roll over, both states stays.
Visible true and false fails
Changing text fails, both old and new text are stays.

Note : These all reproducible if the textfield have any filters like glow etc.,

**Comment by tour1st** [comment] 2018-10-01 14:54
The issue is still there in OpenFL 8.5.1 ( it works correctly in OpenFL 8.3.0 ).

**Sample code to reproduce the issue**
```
import openfl.Lib;
import openfl.events.Event;
import openfl.filters.GlowFilter;
import openfl.text.TextField;
import openfl.text.TextFormat;

static function main()
{
	var t:TextField = new TextField();
	t.x = 50;
	t.y = 50;
	t.textColor = 0x0000FF;
	t.defaultTextFormat = new TextFormat( "Arial", 50 );
	t.filters = [new GlowFilter()];
	Lib.current.stage.addChild( t );
	Lib.current.stage.addEventListener( Event.ENTER_FRAME, function( e:Event )
		{
			t.text = Std.string( Std.int( Lib.getTimer()/1000 ) );
		}
	);
}

```
**Expected result**
Text should display 0, then 1, then 2, etc...

**Current result**
Old texts are not erased.
![image](https://user-images.githubusercontent.com/38788810/46296197-24553700-c59a-11e8-9f09-6e15257503db.png)

**Comment by tour1st** [comment] 2018-10-11 14:36
It looks like the issue is related to the GlowFilter hack removal :
https://github.com/openfl/openfl/commit/61e7ee02517bfc6f452cc478957a647c22f100f5#diff-a6e42bb0f702e824dad4f661af6ac18e

@jgranick Any ideas ?

**Comment by lmodlinski** [comment] 2018-10-21 12:05
@tour1st You sample now works correctly after my PR was merged with some fixes around filters (tested HTML5, hardware), visibility on and off looks OK with following `ENTER_FRAME`. Scaling is though still an issue.

Enter Frame function for Visibility + changing text with filters on:
```
package;

import openfl.display.Sprite;
import openfl.Lib;
import openfl.events.Event;
import openfl.filters.GlowFilter;
import openfl.text.TextField;
import openfl.text.TextFormat;

class Main extends Sprite {
    public function new() {
        super();

        var t:TextField = new TextField();
        t.x = 50;
        t.y = 50;
        t.textColor = 0x0000FF;
        t.defaultTextFormat = new TextFormat( "Arial", 50 );
        t.filters = [new GlowFilter()];
        t.text = 'Lorem Ipsum';

        var time:Int = 0;

        this.stage.addChild(t);
        this.stage.addEventListener(Event.ENTER_FRAME, function(e:Event) {
            if (1000 < Lib.getTimer() - time) {
                t.visible = !t.visible;
                t.text = Lib.getTimer();

                time = Lib.getTimer();
            }
        }
        );
    }
}
```

Rolling over and out with scaling textfield example

```
package;

import openfl.events.MouseEvent;
import openfl.display.Sprite;
import openfl.filters.GlowFilter;
import openfl.text.TextField;
import openfl.text.TextFormat;

class Main extends Sprite {
    public function new() {
        super();

        var t:TextField = new TextField();
        t.x = 50;
        t.y = 50;
        t.width = 100;
        t.height = 100;
        t.textColor = 0x0000FF;
        t.defaultTextFormat = new TextFormat( "Arial", 50 );
        t.filters = [new GlowFilter()];
        t.text = 'Lorem Ipsum';

        this.addChild(t);

        t.addEventListener(MouseEvent.ROLL_OVER, function(_){
            t.scaleX = t.scaleY = 1.5;
        });

        t.addEventListener(MouseEvent.ROLL_OUT, function(_){
            t.scaleX = t.scaleY = 1.0;
        });
    }
}
````

**Comment by MSGhero** [comment] 2021-01-07 04:36
Closing this since it is fixed in general now. Any bugs and edge cases will have shown up recently and would deserve a more recent issue

**Closed by MSGhero** 2021-01-07 04:36 UTC
