### ISSUE TITLE
False mouseMove events generated on OSX with a trackpad

### ISSUE THREAD

**Issue by jskuse** [openfl/openfl#782] opened 2015-08-07 17:16 UTC
Using OpenFL 3.2.2 and Lime 1.5.7 with the Mac target on a Macbook with a trackpad I'm seeing a large number of "false" mouseMove events with incorrect floating point coordinates being generated, outnumbering the valid ones 2 to 1.

Given the following code:
```
class Main {
	public function new () {
		flash.Lib.current.stage.addEventListener(flash.events.MouseEvent.MOUSE_MOVE, function(e) { trace(e.stageX, e.stageY, e.localX, e.localY); });
	}
}
```

The output is:
```
Main.hx:5: 292,312,292,312
Main.hx:5: 0.429977416992188,0.305801391601562,0.429977416992188,0.305801391601562
Main.hx:5: 0.429367065429688,0.30328369140625,0.429367065429688,0.30328369140625
Main.hx:5: 291,311,291,311
Main.hx:5: 0.429367065429688,0.30078125,0.429367065429688,0.30078125
Main.hx:5: 0.42877197265625,0.29827880859375,0.42877197265625,0.29827880859375
Main.hx:5: 291,308,291,308
Main.hx:5: 0.42877197265625,0.295761108398438,0.42877197265625,0.295761108398438
Main.hx:5: 0.42877197265625,0.294097900390625,0.42877197265625,0.294097900390625
Main.hx:5: 291,306,291,306
Main.hx:5: 0.431182861328125,0.294097900390625,0.431182861328125,0.294097900390625
Main.hx:5: 0.436630249023438,0.294097900390625,0.436630249023438,0.294097900390625
Main.hx:5: 296,306,296,306
Main.hx:5: 0.443893432617188,0.294937133789062,0.443893432617188,0.294937133789062
Main.hx:5: 0.45538330078125,0.29827880859375,0.45538330078125,0.29827880859375
Main.hx:5: 320,309,320,309
Main.hx:5: 0.463851928710938,0.299942016601562,0.463851928710938,0.299942016601562
Main.hx:5: 0.4747314453125,0.302459716796875,0.4747314453125,0.302459716796875
```
Looking at the call stack it seems that the rogue events are coming from:
```
NativeApplication.handleTouchEvent (58)
Application.onTouchMove (372)
Stage.onTouchMove (830) 
```

**Comment by jgranick** [comment] 2015-08-27 21:25
This should be resolved with current Lime versions :smile:

**Comment by jgranick** [comment] 2015-08-27 21:25
You should get mouse and touch events for a touch device, and mouse events for a mouse. This is by design, but I think it was possible to get doubles (or events with bad coordinates) which should be fixed

**Closed by jgranick** 2015-08-27 21:25 UTC
