### ISSUE TITLE
Field toString is declared 'override' but doesn't override any field [Flash]

### ISSUE THREAD

**Issue by T1mL3arn** [openfl/openfl#658] opened 2015-05-08 03:59 UTC
Just tried to create custom Error and override toString():
```Haxe
class UserError extends Error
{
	public function new(message:String="", id:Int=0) 
	{
		super(message, id);
		
	}
	
	override public function toString():String 
	{
		return "test!";
	}
}
```

and got
``` src/UserError.hx:18: lines 18-21 : Field toString is declared 'override' but doesn't override any field ```

Compilation error happened for flash. Html5 works fine.

Haxe 3.2-rc2, Lime 2.3.3, OpenFl 3.0.3

**Comment by Gama11** [comment] 2015-05-08 12:46
Interesting problem, can't think of any simple way to fix this on the openfl side. The issue is that OpenFL uses its own implementation of `Error` on all targets but flash (where the native class is used, and you can't override native functions I think).

I guess you could use 

```haxe
#if !flash override #end public function toString():String
```
as a workaround.

**Comment by jgranick** [comment] 2015-05-21 00:58
I'm going to close this for now (as I don't think this is a bug) but I wonder what would happen if we added "toString" to the extern for error, if that would work in ActionScript 3, or not. The only other option here (for total consistency) would be to hack the type using an abstract, so openfl.error.Error (on Flash) is an abstract over flash.error.Error, with the added `toString` method

**Closed by jgranick** 2015-05-21 00:58 UTC

**Comment by Gama11** [comment] 2015-05-21 07:40
@jgranick I've actually tried adding `toString()` to the extern - it made it compile with `override`, but led to a runtime error.

**Comment by T1mL3arn** [comment] 2015-05-21 10:55
Oh, I think flash allows to override Error.toString() but in don't.
