### ISSUE TITLE
Infinite loop in TextEngine.getLayoutGroups()

### ISSUE THREAD

**Issue by mrchnk** [openfl/openfl#2124] opened 2019-01-18 12:16 UTC
I encountered that issue with html5 target on latest haxelib and npm distributions (8.8.0 at moment)

I extracted reproducible project with problematic swf asset at https://github.com/mrchnk/openfl-issue-textengine

That loop:
https://github.com/openfl/openfl/blob/8.8.0/src/openfl/_internal/text/TextEngine.hx#L1083

OS (Windows 10 x64)
Haxelib version 3.3.0
Haxe version 3.4.7

haxelib list
```
openfl-issue-textengine> haxelib list
actuate: [1.8.9]
box2d: [1.2.3]
format: [3.4.1]
hxcpp: [4.0.4]
hxp: [1.0.5]
layout: [1.2.1]
lime-samples: [7.0.0]
lime: 7.2.0 [7.2.1]
openfl-samples: [8.7.0]
openfl: 8.7.0 [8.8.0]
```

**Comment by MSGhero** [comment] 2019-01-18 18:22
I can check this out, although it will be very hard to debug without seeing the TextField in code instead of inside the swf as an asset. If you can reproduce this purely in code (just the TextField and text), that would be helpful.

**Comment by jgranick** [comment] 2019-01-18 19:10
I just added this to `TextField.__fromSymbol`:

```haxe
trace ("----");
		if (symbol.html) trace ("htmlText: " + htmlText);
		if (!symbol.html)trace ("text: " + text);
		trace ("defaultTextFormat: " + defaultTextFormat);
		trace ("multiline: " + multiline);
		trace ("wordWrap: " + wordWrap);
		trace ("displayAsPassword: " + displayAsPassword);
		trace ("border: " + border);
		trace ("background: " + background);
		trace ("selectable: " + selectable);
		trace ("type: " + type);
		trace ("width, height: " + width, height);
```

I ran the sample project, and got this output (before it froze on calculating the width/height):

```
openfl/text/TextField.hx:1710: htmlText: 8888888888


openfl/text/TextField.hx:1712: defaultTextFormat: { bold => false, font => OasisHeader, color => 16777215, size => 24, bullet => false, leftMargin => 0, __ascent => null, tabStops => null, letterSpacing => 0, url => , italic => false, target => , underline => false, leading => -2, indent => 0, __descent => null, align => 3, rightMargin => 0, kerning => false, blockIndent => 0 }
openfl/text/TextField.hx:1713: multiline: false
openfl/text/TextField.hx:1714: wordWrap: false
openfl/text/TextField.hx:1715: displayAsPassword: false
openfl/text/TextField.hx:1716: border: false
openfl/text/TextField.hx:1717: background: false
openfl/text/TextField.hx:1718: selectable: false
openfl/text/TextField.hx:1719: type: dynamic
```

**Comment by MSGhero** [comment] 2019-01-19 00:14
... what

I guess, the more esoteric these bugs get, the closer `getLayoutGroups` is to being correct.

**Comment by dpomier** [comment] 2019-02-25 17:07
Any update on this one?

Simply having a TextField with `"<p></p>"` after some other string seems to reproduce this bug (also on the current development branch of openfl and lime 7.2.1). Like the following:
```haxe
class Main extends openfl.display.Sprite {

    public function new () {
        super();
        var tf = new openfl.text.TextField();
        tf.htmlText = "<p>Hello</p><p></p>";
        addChild(tf);
    }
}
```

I get this in the console of firefox:
```
Error: Script terminated by timeout at:
setFormattedPositions@http://localhost:2000/BacklineIssue.js:49428:11
getLayoutGroups@http://localhost:2000/BacklineIssue.js:49583:5
update@http://localhost:2000/BacklineIssue.js:49865:4
__updateLayout@http://localhost:2000/BacklineIssue.js:69149:4
__renderGL@http://localhost:2000/BacklineIssue.js:68554:5
__renderGL@http://localhost:2000/BacklineIssue.js:3885:6
__renderGL@http://localhost:2000/BacklineIssue.js:3885:6
__renderGL@http://localhost:2000/BacklineIssue.js:3885:6
__render@http://localhost:2000/BacklineIssue.js:56063:4
__onLimeRender@http://localhost:2000/BacklineIssue.js:58581:5
f@http://localhost:2000/BacklineIssue.js:73462:233
dispatch@http://localhost:2000/BacklineIssue.js:14428:16
handleApplicationEvent@http://localhost:2000/BacklineIssue.js:351:6
exec@http://localhost:2000/BacklineIssue.js:327:3
exec@http://localhost:2000/BacklineIssue.js:602:10
ApplicationMain.create@http://localhost:2000/BacklineIssue.js:975:15
$hx_exports.lime.embed@http://localhost:2000/BacklineIssue.js:22175:4
@http://localhost:2000/:43:3
```

Something that may help:
- `"<p>Hello</p><p></p>"` fails
- `"<p></p><p></p>"` works
- `"<p>Hello</p><p>Hello</p>"` works

**Comment by MSGhero** [comment] 2019-03-13 10:54
It sounds like these are two separate issues, as the second one doesn’t look like it has anything to do with SWFs.

**Comment by dpomier** [comment] 2019-03-13 11:25
When there is a line break in the text field of a SWF, it becomes `<p></p>` in OpenFL, which I think could be the origin of the issue

**Comment by MSGhero** [comment] 2019-03-13 11:57
Ahhhhh ok now we’re getting somewhere if that’s correct.

**Comment by MSGhero** [comment] 2019-03-14 02:52
Ok nice, I can replicate this as well with the htmlText `"a<p></p>"`. I'll try to debug it when I can, likely this weekend. Trying to put some coding time back into my week

**Comment by MSGhero** [comment] 2019-03-14 23:35
Temporary fix, haven't compiled units or anything: [htmlparser diff.txt](https://github.com/openfl/openfl/files/2968847/htmlparser.diff.txt)

The issue seems to be that although `<p>` and `</p>` add a newline, the text format ranges are not updated to reflect the fact that you just added a new character to the parsed string. This is in src/openfl/_internal/formats/html/HTMLParser.hx

**Comment by jgranick** [comment] 2019-03-14 23:36
@MSGhero This also looks interesting:

https://github.com/Kixeye/openfl/pull/3/files

**Comment by MSGhero** [comment] 2019-03-14 23:38
@jgranick I was thinking about that recently... but we wouldn't necessarily know if there was an issue, versus a very hard "there's something wrong with text layout." I guess from your perspective, the lib not crashing internally is pretty good :D

**Comment by jgranick** [comment] 2019-03-14 23:42
A `Log.warn` might be a compromise to prevent and infinite loop, but still know that something is not right

**Comment by MSGhero** [comment] 2019-03-16 18:59
![image](https://user-images.githubusercontent.com/5033927/54480202-ff791700-47fb-11e9-997e-4f323d3e0f85.png)
Got it

**Comment by MSGhero** [comment] 2019-03-28 22:31
Well, I haven't committed the fix for this issue specifically, where the format range isn't being adjusted on `<p>`

**Closed** 2019-04-13 21:10 UTC
