### ISSUE TITLE
"haxelib run openfl setup" gives error message on clean install

### ISSUE THREAD

**Issue by TerryCavanagh** [openfl/openfl#882] opened 2015-10-14 17:35 UTC
Heya,

Just did a clean install of haxe and openfl. On the download instructions for openfl (http://www.openfl.org/download/), it gives these two commands to run:

```
haxelib install openfl
haxelib run openfl setup
```

The second command produces this error now:

```
c:\coding\haxe\haxe>haxelib run openfl setup
'"haxelib install lime"' is not recognized as an internal or external command,
operable program or batch file.
Library lime is not installed
```

It's easily fixed by just typing *haxelib install lime* first, but I thought I'd bring it to your attention since it a bug with initial setup and could be a problem for new haxe developers. (This happens on both windows 10 and OSX El Capitan, both of which I tried today.)

**Comment by larsiusprime** [comment] 2015-10-14 18:06
Thanks for finding this pain point!

**Comment by TerryCavanagh** [comment] 2015-10-14 18:21
No problem!

Also worth noting that El Capitan seems to have made usr/ a completely protected directory, so it probably shouldn't be the default installation folder for haxe anymore (though of course that's a haxe thing, not an openfl thing)

**Comment by dagnelies** [comment] 2015-11-06 20:25
I fell in the same trap ...which gave me a rather bad impression to be honest ...the second typed line and already an error

**Comment by jedevc** [comment] 2015-12-04 11:25
Could this possibly be caused by calling [Sys.command](http://api.haxe.org/Sys.html#command) in the wrong way (by calling the whole command in one string instead of using an argument list) in [RunScript.hx](https://github.com/openfl/openfl/blob/master/script/RunScript.hx#L44)?

**Comment by jcward** [comment] 2015-12-08 23:08
FYI, still today exists in 3.5.0.

**Comment by jgranick** [comment] 2015-12-09 01:11
Yeah, this used to work :confused: 

Fixed now, will go out in the next minor release :smile:

**Comment by jcward** [comment] 2015-12-09 04:29
@jgranick Awesome! Hey, so not to be a downer, but the next step in setup, `lime setup windows` didn't work for me today either. Is it because the visual studio url has changed? Things move too fast. :)

**Comment by ibilon** [comment] 2016-04-23 07:57
Original problem soved, if there's still problem with `lime setup windows` please open a new issue.

**Closed by ibilon** 2016-04-23 07:57 UTC

**Comment by nguyenbs** [comment] 2022-08-20 11:41
Its now 2022 and the problem still remained
