### ISSUE TITLE
TextField line break in wrong position (with repro case)

### ISSUE THREAD

**Issue by larsiusprime** [openfl/openfl#1123] opened 2016-05-11 19:47 UTC
Took me a while to get an exact repro case for this!

It should look like this (legacy):
![2016-05-11 14_45_16-bugtextopenfl](https://cloud.githubusercontent.com/assets/739064/15194175/2b87a85a-1787-11e6-8a5c-0ffc6bec0ebb.png)

But it looks like this (next):
![2016-05-11 14_44_20-bugtextopenfl](https://cloud.githubusercontent.com/assets/739064/15194178/30204458-1787-11e6-8a69-3942247b3519.png)

The bug only happens with very specific settings, but it happens consistently when you narrow it down to a proper edge case.

Main.hx

``` haxe
package;

import openfl.text.TextField;
import openfl.text.TextFormat;
import openfl.Assets;
import openfl.display.Sprite;
import openfl.text.TextFormatAlign;

class Main extends Sprite
{
    public function new()
    {
        super();
        var text = new TextField();
        text.x = 10;
        text.y = 10;
        text.width = 528;
        text.height = 235;
        text.border = true;
        text.text = getText();
        text.wordWrap = true;
        text.setTextFormat(new TextFormat("Verdana", 19, 0x000000,null,null,null,null,null,TextFormatAlign.CENTER));
        addChild(text);
    }

    private function getText():String
    {
        return "The elegant yet simple construction of this Ash weapon indicates that it was created for a modest noble.\n\nOne side of the hilt bears the inscription 'Commander of Legions' while the reverse reads 'Servant of the Unmoved Mover.' The disc pommel is engraved on one side with the spheres of the celestial machine and on the other with a pilgrim drinking from the Ash Temple Fountain.";
    }
}
```

project.xml:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<project>
    <!-- NMML reference: https://gist.github.com/1763850 -->

    <!-- metadata, make sure 'package' is at least 3 segments (ie. com.mycompany.myproject) -->
    <meta title="BugTextOpenFL" package="BugTextOpenFL" version="1.0.0" company="" />

    <!-- output -->
    <app main="Main" file="BugTextOpenFL" path="bin" />

    <window background="#FFFFFF" fps="60" />
    <window width="800" height="480" unless="mobile" />
    <window orientation="landscape" vsync="false" antialiasing="0" if="cpp" />

    <!-- classpath, haxe libs -->
    <source path="src" />
    <haxelib name="openfl" />
    <haxelib name="actuate" />

    <!-- assets -->
    <icon path="assets/openfl.svg" />
    <assets path="assets/img" rename="img" />
    <assets path="assets" include="*.ttf" type="font" />

    <!-- optimize output
    <haxeflag name="-dce full" /> -->

</project>
```

Don't forget to put font file "verdana.ttf" from your windows font folder in your root `assets/` directory.

If you can't reproduce it, make sure that you're actually using the Verdana font! Serifed text is a dead giveaway that it's using the system default.

**Comment by MSGhero** [comment] 2016-05-11 20:18
Related to #1094? Still waiting on confirmation about a second change to make.

**Comment by MSGhero** [comment] 2016-05-12 00:46
Partially related to #1094, also something else. But if Flash is our gold standard, then your original case is wrong too. Not sure why the images are different sizes. Irrelevant, though.

Flash:
![image](https://cloud.githubusercontent.com/assets/5033927/15200876/b4f86a9c-17b0-11e6-896c-82d107c39cf0.png)

Neko legacy:
![image](https://cloud.githubusercontent.com/assets/5033927/15200913/01841456-17b1-11e6-92ec-9f2b12f22748.png)

Neko next with #1094:
![image](https://cloud.githubusercontent.com/assets/5033927/15200837/60a0b90e-17b0-11e6-9b5e-bc9a0de4a630.png)

**Comment by MSGhero** [comment] 2016-05-12 00:51
As expected, if I remove "noble" then the second line aligns where it's supposed to, Neko next with the fix
![image](https://cloud.githubusercontent.com/assets/5033927/15200992/bd16adf0-17b1-11e6-860c-14790ae8a218.png)

**Comment by MSGhero** [comment] 2016-05-12 01:16
So in summary @larsiusprime, #1094 fixes half your problems (but it's not finished yet), and there's also a new/this issue when a single-word line is followed by a `\n`. The line has to be centered or right-aligned for this specific thing to happen. `JUSTIFY` is also broken in this case in that the second line ("weapon" through "modest") isn't fully filled with text.

**Comment by larsiusprime** [comment] 2016-05-12 01:23
So if I'm reading this right, this use case helped us deduce some atomic "this causes the bug" bits of logic?

**Comment by MSGhero** [comment] 2016-05-12 01:26
Yep 😄 

Like I said before, flixel and openfl fixes partially happen around Defender's Quest.

**Comment by MSGhero** [comment] 2016-05-12 01:54
Idk how breakpoints work in non-flash targets, but the issue is here https://github.com/openfl/openfl/blob/develop/openfl/_internal/text/TextEngine.hx#L992

Gut feeling is that the newline is messing with the length of `lineWidths` or the current value of `lineIndex`. Someone more familiar with `TextEngine` can take over now 😅

**Comment by tienery** [comment] 2016-05-12 02:26
https://github.com/openfl/openfl/blob/develop/openfl/_internal/text/TextEngine.hx#L584
https://github.com/openfl/openfl/blob/develop/openfl/_internal/text/TextEngine.hx#L780

You're probably wondering why I'm linking these. It's loosely related to #1120 but basically breaks are handled in scenarios where `multiline` is `true` and the text is split up into groups of lines, instead of being an entire paragraph.

Those lines are then adjusted based on the layout group's width. As far as I can tell, there is no issue with the Adjustments. It may also be related to word wrapping (but unsure about that last comment).

**Comment by MSGhero** [comment] 2016-05-12 03:32
In Lars' example, if you make the text everything up to "noble." WITHOUT a newline after it, then in the line I linked, `lineWidths.length` is 3, for the 3 lines of text.

HOWEVER, if you add the `\n` to the end of the string, `lineWidths.length` is 2, even though there are 3 (technically 4) lines. Since the array is shorter than the number of lines, the code probably defaults to the last element of the array to get the offsets of additional lines, which is why the last line lines up exactly with the line before it in the original post.

So then maybe in the lines @tienery linked, there's some incorrect or incomplete logic regarding finding line breaks. But it doesn't have to do with `multiline` because I made that `false` in every test case I've done. `wordWrap` is `true` each time.

**Comment by MSGhero** [comment] 2016-05-12 18:59
Once #1094 gets merged, this is done @larsiusprime

**Comment by larsiusprime** [comment] 2016-05-12 19:44
Music to my ears!!!

**Comment by loudoweb** [comment] 2016-05-17 07:04
Awesome. I needed this fix as well.

**Comment by jgranick** [comment] 2017-01-04 21:12
I have tested, and this is working properly in the current development builds :smile:

**Closed by jgranick** 2017-01-04 21:12 UTC
Labels: bug, target-desktop, target-html5
