### ISSUE TITLE
flash.net.FileReference missing

### ISSUE THREAD

**Issue by delahee** [openfl/openfl#146] opened 2013-11-27 16:19 UTC
Hi, 

flash.net.FileReference is missing from the whole apis, it is not a big miss but you might want to task it.

++

**Comment by jgranick** [comment] 2015-02-20 21:26
I would be happy to discuss this more on the forums or the OpenFL Slack, there are no plans (on my end) to implement this right now, but it could make a great pull request. I'd love to see dialog box / file browse support implemented in Lime 2. Until then, I'm closing this as it's not a bug, but a wishlist item :smile:

**Closed by jgranick** 2015-02-20 21:26 UTC
Labels: enhancement
