### ISSUE TITLE
TextField setSelection  Incorrect selection of cursor in Chinese content 

### ISSUE THREAD

**Issue by cjmxp** [openfl/openfl#1903] opened 2018-05-29 04:50 UTC
TextField setSelection  Incorrect selection of cursor in Chinese content。
```
var test:TextField= new TextField()；
test.type=TextFieldType.INPUT;
test.text = "你好世界！"
test.setSelection(3,3)
```
![openflsetselection](https://user-images.githubusercontent.com/2855349/40638770-c585ec40-633f-11e8-9cba-255d61dce91a.png)

**Comment by MSGhero** [comment] 2018-06-26 12:45
I think this is the same as #1805. I believe I know what the issue is, but I’m working on other things atm.

**Comment by cjmxp** [comment] 2018-06-27 08:40
@MSGhero  Yes, it's really about Unicode

**Comment by MSGhero** [comment] 2020-08-01 20:39
This is fixed on dev.

**Closed by MSGhero** 2020-08-01 20:39 UTC
